import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
   // Intra component styling
  return (
    <div className={styles.container}>
      <Head>
        <title>Blockchain Hunter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, huntingcoder blog, hunting coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='/sc.js' strategy="lazyOnload"></Script> */}

      <main className={styles.main}>
        <div className={styles.imagewrap}>
          {/* <Image className={styles.myImg} src="/homeimg.jfif" width={237} height={158}/> */}
          <img className={styles.myImg} src="/banner1.avif" width={237} height={158} alt="hunting coder" />
        </div>
        <h1 className={styles.title}>
          <span className={styles.dummy}>&lt;Blockchain Hunter/&gt;</span>
        </h1>


        {/* <div className={`${styles1.con} ${styles2.con}`}> */}
        <div>
          <h2 className={styles.h2}>Latest Blogs</h2>
          <div className={styles.overrider}>
            <h3 className={styles.h3}>How to learn Solidity in 2023?</h3>
            <p>Solidity is a language for developing smart Contact</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className={styles.overrider}>
            <h3 className={styles.h3}>How to learn Ehter js in 2022?</h3>
            <p className={styles.p}>Ether js is a framework for developing smart contact</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className={styles.overrider}>
            <h3 className={styles.h3}>How to learn Hardhat in 2023?</h3>
            <p>Hardhat has local environment for deploying and testing smatcontracts</p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  );
}
